let DOMClassNames = () => {
    return {
        employersFormContainer: 'text-center justify-content-center',
        employerFormInput: 'form-control d-inline col-lg-2 mr-1 mt-2',
        employerFormButton: 'btn btn-success align-top d-inline col-lg-2 mr-1 mt-2',
        h2Header: 'text-center justify-content-center',
        mainContainer: 'container col-12',
        employerContainer: 'employer d-flex text-left justify-content-between align-middle mt-2 mb-2',
        employersListContainer: 'text-center justify-content-center col-lg-9 pl-0 pr-0 mx-auto mb-5 mt-5',
        employerFirstName: 'first_name d-inline',
        employerLastName: 'last_name d-inline',
        employerBirthDate: 'birth_date d-inline',
        employerSalary: 'salary d-inline',
        employerButtonChange: 'd-inline btn btn-outline-warning d-inline row-1 mr-2',
        employerButtonDelete: 'd-inline btn btn-outline-danger d-inline row-1',
        employerButtonsContainer: 'd-inline',
        employerContent: 'd-inline align-self-center',
        containerModal: 'containerModal text-center justify-content-center',
        tempFirstName: 'tempFirst_name form-control d-inline col-lg-5 mr-4 mb-4',
        tempLastName: 'tempLast_name form-control d-inline col-lg-5 mr-4 mb-4',
        tempBirthDate: 'tempBirth_date form-control d-inline col-lg-5 mr-4 mb-4',
        tempSalary: 'tempSalary form-control d-inline col-lg-5 mr-4 mb-4',
        tempSave: 'tempSave d-inline align-self-center',
        tempCancel: 'tempCancel d-inline align-self-center',
        buttonsModal: '',
        contentModal: '',
        modalShow: 'd-block',
        modalOpacityShow: 'opacityShow',
        modalOpacityHide: 'opacityHide',
        modalfadeBackground: 'fadeBackground',
        modalDialogMargin: 'modalMargin',
        todosHeader: "header col text-center justify-content-center pb-5 mb-3 mt-1",
        todosFooter: "footer col text-center justify-content-center mb-3 mt-3",
        pageNotFound: "page-not-found col-lg-9 mx-auto d-flex flex-column justify-content-center text-center align-items-center",
        pageNotFoundText: "page-not-found-text",
        pageNotFoundButtons: "page-not-found-buttons",
        pageNotFoundButton: "page-not-found-button btn btn-success",
        preloader: "preloader",
        loader: "loader",
        loginAlready: "login-already col-lg-9 mx-auto d-flex flex-column justify-content-center text-center align-items-center",
        loginRedirectToEmployers: "redirect-employers btn btn-success mr-1",
        loginForm: "login-form",
        emailLogin: "form-control email_login",
        passwordLogin: "form-control password_login",
        loginText: "login-text form-text text-muted",
        loginButton: "login-button btn btn-primary",
        loginRedirToRegist: "login-red-reg d-flex justify-content-end align-items-center mt-4",
        loginRedirToRegistText: "login-red-reg-text mr-2",
        loginRedirToRegistButton: "login-red-reg-button btn btn-outline-secondary",
        employersLogout: "employers-logout col-lg-9 mx-auto d-flex flex-column justify-content-center text-center align-items-center",
        employersLogoutText: "employers-logout-text",
        employersLogoutButtons: "employers-logout-buttons d-flex row align-items-center align-middle justify-content-between",
        employersLogoutButton: "employers-logout-button btn btn-success mr-2",
        logoutRegisteredAlready: "logout-registered-already registred-already",
        logoutRegisteredAlreadyText: "registred-already-text col-lg-9 mx-auto d-flex flex-column justify-content-center text-center align-items-center",
        logoutRegisteredAlreadyButtons: "registred-already-buttons d-flex row align-items-center align-middle justify-content-center",
        logoutRegisteredAlreadyButton: "registred-already-button registred-already-buttons btn btn-success",
        RegistrationContainer: "registration-container container",
        RegistrationContainerRow: "registration-container__row",
        RegistrationRowCol: "registration__row col-md-12",
        RegistrationColH1: "registration-col__h1 text-center mb-5",
        RegistrationColLg12: "col-lg-12 pr-0 pl-0",
        RegistrationCol: "col pr-0 pl-0",
        RegistrationCard: "reg-card card border-secondary",
        RegistrationCardHeader: "card-header",
        RegistrationCardHeaderH3: "mb-0 my-2",
        RegistrationCardBody:"card-body",
        RegistrationFormGroup: "reg-form-group form-group",
        RegistrationFormControl: "reg-form-control form-control",
        RegistrationFormButton: "reg-form-button btn btn-success btn-lg float-right",
        employersListLogoutFrom: "employers-logout-form logout-form d-flex justify-content-center align-items-center",
        employersListLogout: "employers-list-logout btn btn-outline-secondary btn-sm",
        employersListLogoutContent: "employers-logout-content logout-form-content",
        employersLogin: "employers-login",
        employersLoginContainer: "employers-login col-lg-9 mx-auto d-flex flex-column justify-content-center text-center align-items-center",
        employersLoginText: "employers-login-text",
        employersLoginButtons: "employers-login-buttons",
        employersLoginButtonLogin: "employers-login-button btn btn-success mr-2",
        employersLoginButtonReg: "employers-reg-button btn btn-success mr-2",
        modalWindow: "modal fade",
        modalWindowDialog: "modal-dialog",
        modalWindowContent: "modal-content",
        modalWindowContenth5: "modal-header",
        modalWindowContentTitle: "modal-title",
        modalWindowClose: "close",
        modalWindowBody: "modal-body",
        modalWindowFooter: "modal-footer",
        modalWindowFooterButtonClose: "button-close-modal btn btn-secondary",
        modalWindowFooterButtonSave: "button-save-modal btn btn-primary"
    }
};

export default DOMClassNames;